title:              Ted Blog
email:              ckyuhyun@gmail.com
description:        This is a place where I would like to share or keep what I've learnt.
author:             Ted
baseurl:            "/"
url:                "https://ckyuhyun.github.io/"

# Social Profiles
twitter_username:   
github_username:    ckyuhyun
facebook_username:  
instagram_username:  
linkedin_username: kyuhyun-cho-32b010102

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
